blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/iOfficeAI/AionUi/discussions
    about: Ask questions, share ideas, and discuss AionUi with the community
  - name: 📖 Documentation
    url: https://github.com/iOfficeAI/AionUi/wiki
    about: Check our documentation for setup guides, configuration, and troubleshooting
  - name: 🔒 Security Issues
    url: mailto:security@aionui.com
    about: Report security vulnerabilities privately (DO NOT create public issues)
