name: ✨ Feature Request
description: Suggest an idea for AionUi
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: What problem or limitation would this feature address?
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: dropdown
    id: feature_category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - UI/UX Improvement
        - AI Model Integration
        - File Management
        - Multi-Agent Support
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
      placeholder: Use cases, examples, mockups, etc.
