name: ❓ Question
description: Ask a question about AionUi
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: question_category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Installation & Setup
        - Configuration
        - Usage & Features
        - Troubleshooting
        - Development
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about your question. What are you trying to achieve?
      placeholder: Describe what you're trying to do or understand...

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows
        - Linux
        - Not applicable
